### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by MartinX3** [linuxserver/docker-duckdns#53] opened 2022-11-04 16:45 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
According to https://www.duckdns.org/spec.jsp the API of DUCKDNS looks like
`https://www.duckdns.org/update?domains={YOURVALUE}&token={YOURVALUE}[&ip={YOURVALUE}][&ipv6={YOURVALUE}][&verbose=true][&clear=true]`

This container uses https://github.com/linuxserver/docker-duckdns/blob/be0738ce539786c994f7d952affe622fd8c67073/root/app/duck.sh#L4

By appending `&ipv6={YOURVALUE}` to the call we could define our IPv6.

But the problem is the changing IPv6 prefix.
The host needs to inform the container about the new IPv6 address.

In my case I use systemd-networkd.
According to `ip addr` I got `inet6 2a0a:...` and `inet6 fe80:...` where the 2a0a one is the public address.

## Current Behavior
No usage of the IPv6 API value

## Alternatives Considered
If the IPv6 doesn't change you can add it in the web interface.
But not if it changes on a daily base (changing provider prefix).

**Comment by qq380495995** [comment] 2022-12-11 00:59
我不需要更新路由器或网关的ipv6，
我需要更新服务器本地的ipv6，
请给出配置参数，谢谢。
I don't need to update the IPv6 of my router or gateway,
I need to update the IPv6 local to the server,
Please give the configuration parameters, thank you.

**Comment by codyc1515** [comment] 2022-12-11 07:31
Duplicate of #39

**Comment by Mainfrezzer** [comment] 2023-02-22 10:39
Do love the container, but was also missing the ipv6 support. i just jerry-rigged dual stack/ipv6 only support up.

https://github.com/Mainfrezzer/docker-duckdns-Dual-Stack-Support


Rather quick to do it yourself.

**Comment by drizuid** [comment] 2023-03-26 16:07
closing as this is a duplicate of https://github.com/linuxserver/docker-duckdns/issues/39

**Closed as not planned by drizuid** 2023-03-26 16:07 UTC
